language: ruby
rvm:
  - "2.3.1"
addons:
  postgresql: "9.6"
before_script:
  - psql -c 'create database joss_test' -U postgres
  - bundle install
  - bundle exec rake db:structure:load

script: bundle exec rake
